name: iOS Build
on:
  push:
    branches: [ main ] # Перевір, чи твоя головна гілка називається main, а не master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-bundle
          path: build/ios/iphoneos/*.app